### ISSUE TITLE
Which scopes should we check

### ISSUE THREAD

**Issue by yann120** [pixelastic/prst#6]
Hey :) 
In the readme, you ask to generate a tokens
But there is a lot of scopes that can be checked.
Which one should we check ? 
Adding this in the readme could be awesome!
Thanks

**Comment by pixelastic** [comment]
Thanks for raising the issue. The actual needed scopes are `repo` and `workflow`. I added that to the README as well.

**Comment by yann120** [comment]
Cool thanks!
