### ISSUE TITLE
Feature request: Run the script in background and have a notification with the result when tests are done

### ISSUE THREAD

**Issue by yann120** [pixelastic/prst#7]
Hey,
What do you think to add a notification with the result when the CI has finished to run the test ? 
Do you know if it's technically possible to send a push notification to the mac or a slack notification ?
That could be the next step 🔥

**Comment by pixelastic** [comment]
Hey,

Regarding the notification, it should already do that actually. The library I'm using claims to work on both Mac and Linux. I could only test on Linux, though. Are you running on Mac and failing to see the notification?

As for running in the background, I think you could already do it with `prst &`. The `&` should put it in the background. I havent' test it, though.

Finally, regarding the Slack notification I think it would be possible; there are a lot of Slack API clients available. But I'm pretty sure there already exists Slack extensions that you could connect to GitHub directly without needing `prst`.

**Comment by yann120** [comment]
Hey :) 
So the notification on mac doesn't work for me, or maybe because I run it from the VScode terminal.
I will try next week with Iterm.

The only thing that it do is open the webpage of the PR when the CI is done.

And good idea for & to run it in background 👍

**Comment by pixelastic** [comment]
@timothedelion managed to have notifications working on Mac recently; he updated the readme with the additional library you need to install
